name: "Required review check"
on:
  # pull_request_target is suggested for projects where pull requests will be
  # made from forked repositories. If pull_request is used in these cases,
  # the github token will not have sufficient permission to update the PR.
  pull_request_review:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read # to read changed files
  pull-requests: write # to read/write PR reviewers
  statuses: write # to add the status pass/fail

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest

    # GitHub should provide a "pull_request_review_target", but they don't and
    # the action will fail if run on a forked PR.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - uses: Automattic/action-required-review@93a995cac9308b74ef0c91c0d3ee8ded6bb9c2fe
        with:
          token: ${{ github.token }}
          requirements-file: .github/required-review.yml
          request-reviews: true
          status: Required review
